/**
 * Claude Usage Panel API
 * 
 * Reads claude-usage.json from workspace (generated by claude-usage-monitor skill)
 * Returns null if file doesn't exist (panel will hide itself)
 */

const fs = require('fs');
const path = require('path');

module.exports = ({ hooks, auth, config }) => ({
  endpoint: '/api/panels/claude-usage',
  handler: async (req, res) => {
    let user = req.body?.initData
      ? auth.validateInitData(req.body.initData)
      : auth.getUserFromCookie(req);
    
    if (!user || !auth.isAllowed(user.id)) {
      return res.status(403).json({ error: 'Unauthorized' });
    }

    const WORKSPACE = path.resolve(__dirname, '..', '..', '..', '..');
    const usagePath = path.join(WORKSPACE, 'claude-usage.json');

    try {
      const data = JSON.parse(fs.readFileSync(usagePath, 'utf8'));
      res.json(hooks.filter('panel.claude-usage.data', data));
    } catch {
      res.json(null);
    }
  }
});
